# Generated by Django 5.0 on 2024-08-14 14:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gNB_ID', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('axis', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('height', models.FloatField()),
                ('azimuth', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='DataManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(default='uploads/2024-08-14', max_length=100)),
                ('file', models.FileField(upload_to='uploads/2024-08-14')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Save time')),
            ],
        ),
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ue_id', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('serv_pci', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('serv_rsrp', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('serv_rsrq', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('serv_sinr', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('serv_ta', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('serv_rssi', models.SmallIntegerField()),
                ('reserve_1', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reserve_2', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_pci_1', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrp_1', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrq_1', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_sinr_1', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_pci_2', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrp_2', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrq_2', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_sinr_2', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_pci_3', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrp_3', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrq_3', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_sinr_3', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_pci_4', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrp_4', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrq_4', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_sinr_4', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_pci_5', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrp_5', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrq_5', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_sinr_5', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='MobileBaseStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.BigIntegerField()),
                ('imsi', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UEInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ueid', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Save time')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Last modified time')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PciBaseStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pci', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('base_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.basestation')),
            ],
        ),
    ]
