# Generated by Django 5.0 on 2024-09-02 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDataManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(default='uploads/2024-09-02', max_length=100)),
                ('file', models.FileField(upload_to='uploads/2024-09-02')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Save time')),
            ],
        ),
        migrations.AlterField(
            model_name='datamanager',
            name='file',
            field=models.FileField(upload_to='uploads/2024-09-02'),
        ),
        migrations.AlterField(
            model_name='datamanager',
            name='relative_path',
            field=models.CharField(default='uploads/2024-09-02', max_length=100),
        ),
    ]
