# Generated by Django 5.0 on 2024-09-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_trainingdatamanager_alter_datamanager_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdatamanager',
            name='file',
            field=models.FileField(upload_to='uploads/training_data/2024-09-02'),
        ),
        migrations.AlterField(
            model_name='trainingdatamanager',
            name='relative_path',
            field=models.CharField(default='uploads/training_data/2024-09-02', max_length=100),
        ),
    ]
