# Generated by Django 5.0 on 2024-06-24 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsigned_message_count', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ue_id', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('pci_0', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rsrp_0', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('pci_1', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rsrp_1', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('pci_2', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rsrp_2', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('pci_3', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rsrp_3', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
