# Generated by Django 5.0 on 2024-06-25 15:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enci', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('height', models.FloatField()),
                ('azimuth', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='MobileBaseStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.BigIntegerField()),
                ('imsi', models.BigIntegerField()),
                ('base_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo1.basestation')),
            ],
        ),
        migrations.CreateModel(
            name='PciBaseStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pci', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('base_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo1.basestation')),
            ],
        ),
    ]
