# Generated by Django 5.0 on 2024-06-26 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0002_basestation_mobilebasestation_pcibasestation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ue_id', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('serv_pci', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('serv_rsrp', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('serv_rsrq', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('serv_sinr', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('serv_ta', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('serv_rssi', models.SmallIntegerField()),
                ('reserve_1', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reserve_2', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_pci_1', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrp_1', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrq_1', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_sinr_1', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_pci_2', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrp_2', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrq_2', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_sinr_2', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_pci_3', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrp_3', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrq_3', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_sinr_3', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_pci_4', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrp_4', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrq_4', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_sinr_4', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_pci_5', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrp_5', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_rsrq_5', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nbr_sinr_5', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.RemoveField(
            model_name='mobilebasestation',
            name='base_station_id',
        ),
    ]
