# Generated by Django 5.0 on 2024-07-25 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0003_locationinfo_delete_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basestation',
            old_name='enci',
            new_name='gNB_ID',
        ),
        migrations.AddField(
            model_name='basestation',
            name='axis',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
