# Generated by Django 5.0 on 2024-08-02 10:24

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0004_rename_enci_basestation_gnb_id_basestation_axis'),
    ]

    operations = [
        migrations.CreateModel(
            name='UEInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ueid', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Save time')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Last modified time')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
    ]
